# Generated by Django 4.2.2 on 2023-06-10 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_usergroupmember',
            name='ExpiryDate',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
